baseURL = 'https://pengdongbo.github.io/'
locale = 'en-US'
defaultContentLanguage = 'en'
title = 'pengdongbo | Personal Website'
disableKinds = ['taxonomy', 'term', 'RSS']
[params]
  name = 'pengdongbo'
  description = 'Personal website of pengdongbo'
  github = 'https://github.com/pengdongbo'
