baseURL = 'https://pengdongbo.github.io/'
locale = 'en-US'
defaultContentLanguage = 'en'
title = 'Dongbo Peng | Personal Website'
disableKinds = ['taxonomy', 'term', 'RSS']
[params]
  name = 'Dongbo Peng'
  description = 'Personal website of Dongbo Peng'
  github = 'https://github.com/pengdongbo'
